INSERT OR REPLACE INTO work_catalog(id,position,title,category,icon,custom,active) VALUES
('tractor',1,'Trator e máquinas agrícolas','Máquinas agrícolas','🚜',0,1),
('fuel',2,'Combustível','Combustível','⛽',0,1),
('food',3,'Alimentos','Alimentos','📦',0,1),
('drinks',4,'Bebidas','Bebidas','🥤',0,1),
('timber',5,'Madeira e toras','Madeira','🪵',0,1),
('container',6,'Contêiner','Contêiner','🚢',0,1),
('heavy_machine',7,'Máquinas pesadas','Máquinas pesadas','🏗️',0,1),
('vehicles',8,'Veículos','Veículos','🚗',0,1),
('motorcycles',9,'Motocicletas','Motocicletas','🏍️',0,1),
('chemicals',10,'Produtos químicos','Químicos','🧪',0,1),
('construction',11,'Material de construção','Construção','🧱',0,1),
('steel',12,'Aço e metais','Metais','⚙️',0,1),
('paper',13,'Papel e celulose','Papel','📄',0,1),
('electronics',14,'Eletrônicos','Eletrônicos','💻',0,1),
('furniture',15,'Móveis','Móveis','🪑',0,1),
('glass',16,'Vidro','Vidro','🪟',0,1),
('pipes',17,'Tubos','Tubos','🔩',0,1),
('cables',18,'Cabos e bobinas','Cabos','🧵',0,1),
('industrial',19,'Equipamento industrial','Industrial','🏭',0,1),
('mining',20,'Minério e carvão','Mineração','⛏️',0,1),
('grain',21,'Grãos e cereais','Grãos','🌾',0,1),
('rural',22,'Animais e produtos rurais','Rural','🐄',0,1),
('dairy',23,'Leite e laticínios','Laticínios','🥛',0,1),
('medical',24,'Medicamentos e material médico','Médico','⚕️',0,1),
('scrap',25,'Sucata e recicláveis','Recicláveis','♻️',0,1),
('road_machine',26,'Máquinas rodoviárias','Rodoviário','🚧',0,1),
('boats',27,'Barcos e iates','Barcos','⛵',0,1),
('aircraft',28,'Aeronaves e helicópteros','Aeronaves','🚁',0,1),
('refrigerated',29,'Carga refrigerada','Refrigerada','❄️',0,1),
('custom',30,'Carga personalizada','Personalizada','⭐',1,1);
