from pathlib import Path

p=Path('worker.js')
s=p.read_text(encoding='utf-8')
marker=" if(p==='/api/site/admin/session'&&m==='POST'){const b=await body(req),s=await requireAdmin(req,env,b);return json(req,{ok:true,user:s.user,role:s.role})}"
insert=""" if(p==='/api/public/notice'&&m==='GET'){const rows=await env.DB.prepare(\"SELECT key,value FROM meta WHERE key IN ('site_notice_enabled','site_notice_title','site_notice_message','site_notice_updated_at')\").all(),v=Object.fromEntries((rows.results||[]).map(x=>[x.key,x.value]));return json(req,{ok:true,enabled:v.site_notice_enabled==='1',title:v.site_notice_title||'AVISO GAT',message:v.site_notice_message||'',updated_at:v.site_notice_updated_at||null})}\n if(p==='/api/site/admin/notice'&&m==='POST'){const b=await body(req),a=await requireAdmin(req,env,b);if(b.save){const title=String(b.title||'').trim().slice(0,80),message=String(b.message||'').trim().slice(0,600),enabled=b.enabled?1:0;if(enabled&&!message)throw new HttpError(400,'notice_message_required');const t=now();await env.DB.batch([env.DB.prepare(\"INSERT INTO meta(key,value) VALUES('site_notice_enabled',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value\").bind(String(enabled)),env.DB.prepare(\"INSERT INTO meta(key,value) VALUES('site_notice_title',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value\").bind(title||'AVISO GAT'),env.DB.prepare(\"INSERT INTO meta(key,value) VALUES('site_notice_message',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value\").bind(message),env.DB.prepare(\"INSERT INTO meta(key,value) VALUES('site_notice_updated_at',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value\").bind(t)]);await audit(env,a.user,'site_notice',a.user,{enabled:!!enabled,title:title||'AVISO GAT'});return json(req,{ok:true,enabled:!!enabled,title:title||'AVISO GAT',message,updated_at:t})}const rows=await env.DB.prepare(\"SELECT key,value FROM meta WHERE key IN ('site_notice_enabled','site_notice_title','site_notice_message','site_notice_updated_at')\").all(),v=Object.fromEntries((rows.results||[]).map(x=>[x.key,x.value]));return json(req,{ok:true,enabled:v.site_notice_enabled==='1',title:v.site_notice_title||'AVISO GAT',message:v.site_notice_message||'',updated_at:v.site_notice_updated_at||null})}\n"""+marker
if "/api/public/notice" not in s:
    if marker not in s: raise SystemExit('marcador admin session nao encontrado')
    s=s.replace(marker,insert,1)
p.write_text(s,encoding='utf-8')
print('Avisos do site aplicados.')
