plugins { id 'com.android.application' }

android {
    namespace 'com.gatlog.dash'
    compileSdk 35

    defaultConfig {
        applicationId 'com.gatlog.dash'
        minSdk 26
        targetSdk 35
        versionCode 3
        versionName '1.1.1'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
        }
        debug { debuggable true }
    }
}
